VS1-Initial Slice
R2D2-2018/NAVIGATION pull request #2
Opened 2018-05-22 10:15 UTC by Michelbaartman

https://trello.com/c/KNALZKBp/2-vs1-initial-slice

2018-05-23 20:58 UTC, wvanbreukelen requested changes
Please update the code according to the placed comments throughout the code. Have a look at the code guidelines placed on the wiki.

2018-05-23 20:58 UTC, wvanbreukelen commented on src/Command.hpp
> +/**
As specified by the [definition of done](https://github.com/R2D2-2018/R2D2-2018/wiki/Definition-of-Done), code should be documentated. Unfortunately, in the (abstract) classes you have included within your pull request, this is not the case. Please document the future function of your class methods as specified on the [wiki](https://github.com/R2D2-2018/R2D2-2018/wiki/Code-standard).

2018-05-23 20:58 UTC, wvanbreukelen commented on src/main.cpp
> +#include "IO_Interface.hpp"
Please write the filenames in the naming format specified on the [wiki](https://github.com/R2D2-2018/R2D2-2018/wiki/Code-standard).

2018-05-23 20:58 UTC, wvanbreukelen commented on src/IO_Interface.hpp
> +  public:
Be consistent in your spacing. *For each indent 4 spaces will be used.*, [wiki](https://github.com/R2D2-2018/R2D2-2018/wiki/Code-standard#indentation)

2018-05-24 14:31 UTC, Qperquin commented
Requested changes have been made.

2018-05-27 15:19 UTC, wvanbreukelen approved these changes

2018-05-27 17:36 UTC, merged