VS2-Abstract sensor & path class
R2D2-2018/NAVIGATION pull request #8
Opened 2018-05-28 11:30 UTC by Michelbaartman

https://trello.com/c/fcLwPy7y/13-vs2-abstract-sensor-path-class

2018-05-30 13:50 UTC, wvanbreukelen requested changes
Please see the placed comments. If you have any questions, feel free to ask.

2018-05-30 13:50 UTC, wvanbreukelen commented on BuildModule.cmake
> +include (../../toolchain/targets/arm32/cm3/atmel/sam3x/sam3x8e/sam3x8e.cmake)
Why would you hardcode this path?

2018-05-30 13:50 UTC, wvanbreukelen commented on src/main.cpp
> +    const int8_t address = 0x68;
Tip: could be a uint8_t

2018-05-30 13:50 UTC, wvanbreukelen commented on src/memory_map.hpp
> + * @brief       This header will contain memory addresses
I would note it as: This header will contain memory addresses for the MPU9250

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    /*for (;;) {
Please remove debugging statements, or place them into a callable method.

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.hpp
> +     * @return int16_t Gyroscope values
No return type

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.hpp
> +     * @return int16_t Gyroscope values
No return type

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.hpp
> +     * @return int16_t Magnetometer values
No return type

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.hpp
> +    MPU9250Interface(hwlib::pin_oc &scl, hwlib::pin_oc &sda, const int8_t MPUAddr)
Tip: could be a ```uint8_t```

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.hpp
> +    const int8_t MPUAddr;
Tip: could be a ```uint8_t```

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    i2c.write(AK8963_CNTL1, continious, 1);           // start continious mode AK8963
Grammar issues within this section

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    i2c.write(INT_PIN_CFG, bypass, 1); // set bypass mode
Why don't directly place the byte into the write method. Like:
```cpp
i2c.write(INT_PIN_CFG, 0x22, 1); // set bypass mode
```

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    printValuesX_Y_Z(gyroValue);
Please return the gyroValue array and print outside of your method.

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    printValuesX_Y_Z(magnValue);
Please return the magnValue array and print outside of your method.

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +void MPU9250Interface::printValuesX_Y_Z(int16_t temp[3]) {
You would need these methods if you print outside your class.

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_path.hpp
> +     * gets the current length of the path.
I would just remove this extended documentation. It says exactly the same as the sentence above it.

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_path.hpp
> +    Vector2f path[50];
Tip: currently the path is limited to 50 items. Maybe you could make the class a template class and make it a template parameter?

2018-05-30 13:50 UTC, wvanbreukelen commented on src/main.cpp
> +    return 0;
Why would you return if the engine.run() method will run forever

2018-05-30 13:50 UTC, wvanbreukelen commented on src/mpu9250_interface.cpp
> +    uint8_t data[6] = {0x3B}; ///< address where MPU data starts
Why don't place this address within your memory map?

2018-05-30 13:50 UTC, wvanbreukelen commented on test/test_main.cpp
>  TEST_CASE("Example Test Case") {
Please remove the example test case

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_path.hpp
> +class NavigationPath {
Please start the ```@brief``` sections with a uppercase character, like: ```@brief Creates a NavigationPath object.```

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_path.cpp
> +    auto nextLocation = path[head];
I would prefer ```Vector2f``` instead of using ```auto```

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_path.hpp
> +#include <vector>
You cannot make use of <vector>, as it is disabled (heap not functioning).

2018-05-30 13:50 UTC, wvanbreukelen commented on src/navigation_engine.cpp
> +#include <string>
You cannot make use of <string>, as it is disabled (heap not functioning).

2018-06-03 11:01 UTC, wvanbreukelen approved these changes

2018-06-03 11:03 UTC, wvanbreukelen commented
Test is failing, please contact the leads if your team cannot resolve it by themselves.

2018-06-03 12:15 UTC, Qperquin commented
Branch updated to include latest .fetch shell update. Tests now succeed.

2018-06-04 10:54 UTC, merged

2018-06-04 10:55 UTC, Michelbaartman commented
Merging pull request as @wvanbreukelen has approved the changes.